language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
before_script:
  - npm install -g grunt-cli
deploy:
  provider: npm
  email: w@28.io
  api_key: 1pbeVHg2wMqrrcFDUDkR
  on:
    branch: master
    repo: git@github.com:wcandillon/xqlint.git
