language: node_js
node_js:
- '0.11'
- '0.10'
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm 
  email: w@28.io
  api_key:
    secure: sptzco/DP3GmZ7N2tNYQ3Oek5nyZNc4byyWM+Pyt0yjQ0FGKlAVtkekIABmQrjf23AGZ1Y7uF9/AuLFpyQu4f9WMgXYJ1Orp06AVI7aksxyHyMpQXSpHpNIXyy/doMCzymnaVBTaME8exPli3BiJ30WkWQGZlQyVzAwV0vlSj5k=
  on: 
    repo: wcandillon/xqlint
    branch: master
    node: 0.11
